# Log parameters
logID : '2024-02-28-15-54-14'           # Unique identifier for the log
is3D : True                             # Set to True if the point cloud is 3D
initialTimeStep : 1                     # Initial time step to start the simulation
simHorizon : 4934                       # If 0, it runs until the end of the log

# SLAM parameters
isSLAM : True                           # If True, it computes x_t using SLAM
velTracking : False                     # If True, it tracks the velocity to improve the first guess of the SLAM algorithm
numTimeStepsSLAM : 1                    # Number of time steps to use ground truth x_t before starting SLAM
startPoseSLAM : [520, 500, 0]           # Initial pose for the SLAM algorithm if x_t is not available

# Plotting parameters
saveVideo : True                        # If True, it saves the video
removeFrames : False                    # If True, it removes the frames after saving the video
saveSvg : True                          # If True, it saves each frame as a SVG file
videoSection : 'Following'              # Section of the map to plot: 'Full', 'Following', 'Constant'
videoWidth : 100                        # Width of the following window
videoHeight : 50                        # Height of the following window
videoOrigin : [500,475]                 # Origin of the video
style : 'combined'                      # Style of the plot: 'combined', 'static', 'dynamic', 'weather'

# Grid parameters
origin : [0,0]                          # Origin of the grid
width : 1000                            # Width of the grid
height : 1000                           # Height of the grid
resolution : 0.5                        # Resolution of the grid

# TGM parameters
staticPrior : 0.3                       # If 0, it assumes that all the elements are dynamic
dynamicPrior : 0.3                      # If 0, it behaves like a regular grid map
weatherPrior : 0                        # If 0, it assumes no weather noise
maxVelocity : 1                         # Maximum velocity of the agents, used to compute the kernel of the TGM
saturationLimits : [0, 0.95, 0.05, 1]   # Saturation limits for the TGM
fftConv : True                          # If True, it uses FFT to compute the convolution

# Filter parameters
groundThreshold : -1.5                  # Threshold to consider a point as ground
skyThreshold : 1                        # Threshold to consider a point as sky
minDistance : 2                         # Minimum distance to consider a point
maxDistance : 100                       # Maximum distance to consider a point
angRes : 360                            # Angular resolution of the sensor

# Inverse Sensor Model parameters
smWidth : 200                           # Width of the inverse sensor model
smHeight : 200                          # Height of the inverse sensor model
sensorRange : 100                       # Maximum range of the sensor
invModel : [0.1, 0.9]                   # High and low values of the beam inverse sensor model
freeUpGroundDetections : True          # If True, it frees up the ground detections