# Log parameters
logID : '2024-03-15-11-25-54'
is3D : True
initialTimeStep : 1
simHorizon : 10000

# SLAM parameters
isSLAM : True
numTimeStepsSLAM : 1
startPoseSLAM : [500, 500, 0]

# Plotting parameters
saveVideo : False
followingVideo : True
followingWidth : 100
followingWeight : 100

# Grid parameters
origin : [0,0]
width : 1000
height : 1000
resolution : 4

# TGM parameters
staticPrior : 0.3
dynamicPrior : 0.3
weatherPrior : 0
maxVelocity : 1
saturationLimits : [0, 0.95, 0.05, 1]
fftConv : True

# Filter parameters
groundThreshold : -1.5
skyThreshold : 1
minDistance : 2
maxDistance : 30
angRes : 360

# Sensor Model parameters
smWidth : 100
smHeight : 100
sensorRange : 50
invModel : [0.1, 0.9]